### ISSUE TITLE
Question: Recommended way to deal with decorators in async unit tests, e.g. `@pytest.mark.asyncio`

### ISSUE THREAD

**Issue by afuetterer** [provinzkraut/unasyncd#15]
Hi there,

I am a new user of this project. I am not sure, if I missed something in the documentation. Can you recommended how to deal with async unit tests?

For example when running on:

```python
import pytest
from src import AsyncClient

@pytest.mark.asyncio()
async def test_async_client():
    async_client = AsyncClient()
    response = await async_client.get()
    assert response
```

 I get:

```python
import pytest
from src import AsyncClient

@pytest.mark.asyncio()
def test_async_client():
    client = Client()
    response = client.get()
    assert response
```

How can I remove `@pytest.mark.asyncio` in this case? Any hints would be appreciated.

**Comment by provinzkraut** [comment]
Hi @afuetterer, thanks for bringing this up! 

I can think of a few ways to handle this:

1. Use pytest-asyncio in [auto mode](https://pytest-asyncio.readthedocs.io/en/latest/concepts.html#auto-mode). This doesn't require you to use the `pytest.mark.asyncio` marker
2. Don't use separate test for sync/async, and instead add a shim that can deal with awaitables / non-awaitables, and use a fixture to parametrise your tests
3. Unasyncd adds a configuration to remove things instead of replacing them

**How to implement approach No.2**:

```python
import inspect
import pytest
from src import AsyncClient, Client

async def maybe_async(obj):
    return await obj if inspect.isawaitable(obj) else obj


@pytest.fixture(args=[AsyncClient, Client]):
def client(request):
     client_cls = request.param
     return client_cls()


async def test_client(client):
    response = await maybe_async(client.get())
    assert response
```

<hr>

Personally, I use approach number 2 for most of my projects, but number 1 should work as well.

Let me know if you'd prefer approach number 3, and I could check what it would take to implement that, I think it should be rather straightforward.

**Comment by afuetterer** [comment]
Thanks for the fast reply @provinzkraut!

I tried suggestion 1) and it works fine, thanks a lot. I ran into another issue. Should I open a new issue? This one can be closed.
