### ISSUE TITLE
pre-commit: replace `black` with `ruff format`

### ISSUE THREAD

**Issue by afuetterer** [provinzkraut/unasyncd#18]
In your `.pre-commit-config.yaml` you use black and ruff.

https://github.com/provinzkraut/unasyncd/blob/ab7948eae27581d52a84a86d53d8fbf1b4d8b978/.pre-commit-config.yaml#L14-L23

Instead of black you can use the ruff code formatter. It generates the same results and you have fewer dependencies.

What do you think? I can submit a PR, if you like.

Ref: https://docs.astral.sh/ruff/formatter/

**Comment by provinzkraut** [comment]
Sure, makes sense. We've made the switch a while ago over in https://github.com/litestar-org/litestar/pull/2536 and I'm using it for most new projects now :)

> It generates the same results and you have fewer dependencies.

Not entirely true (there are some [intentional deviations](https://docs.astral.sh/ruff/formatter/black/)), but I'm fine with the changes. Needing fewer tools is always nice
